import type { Metadata } from "next";
import { Fustat } from "next/font/google";
import "../globals.css";
import PublicHeader from "@/components/shared/header/header";

const fustat = Fustat({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Native Med",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fustat.className} h-full antialiased`}>
      <body className="min-h-full">
        <PublicHeader />
        {children}
      </body>
    </html>
  );
}
